"""
Configuration for webOS Update Server
"""
from pathlib import Path

# Server settings
HOST = "0.0.0.0"
PORT = 8080
DEBUG = True

# Paths
BASE_DIR = Path(__file__).parent
PACKAGES_DIR = BASE_DIR / "packages"
CERTS_DIR = BASE_DIR / "certs"

# Server identity
SERVER_ID = "webos-update-server"
SERVER_URL = f"http://localhost:{PORT}/palmcsext/swupdateserver"

# Default credentials (from device DmTree.xml)
DEFAULT_USERNAME = "guest"
DEFAULT_PASSWORD = "guestpassword"
SERVER_USERNAME = "omadm.swupdate.palm.com"
SERVER_PASSWORD = "serverguestpassword"

# Update configuration
UPDATE_VERSION = "3.0.6"  # Version to offer
UPDATE_BUILD = "1000"     # Build number to offer

# SyncML Status Codes
class StatusCode:
    SUCCESS = 200
    ITEM_ADDED = 201
    ACCEPTED_FOR_PROCESSING = 202
    NON_AUTHORITATIVE = 203
    NO_CONTENT = 204
    RESET_CONTENT = 205
    PARTIAL_CONTENT = 206
    CONFLICT = 208
    GONE = 210
    AUTH_ACCEPTED = 212
    CHUNKED_ITEM_ACCEPTED = 213
    OPERATION_CANCELLED = 214
    NOT_EXECUTED = 215
    ATOMIC_ROLLBACK_OK = 216

    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404
    COMMAND_NOT_ALLOWED = 405
    OPTIONAL_FEATURE_NOT_SUPPORTED = 406
    MISSING_CREDENTIALS = 407
    REQUEST_TIMEOUT = 408
    INCOMPLETE_COMMAND = 412
    REQUEST_ENTITY_TOO_LARGE = 413
    URI_TOO_LONG = 414
    UNSUPPORTED_MEDIA_TYPE = 415
    REQUEST_SIZE_TOO_BIG = 416
    RETRY_LATER = 417
    ALREADY_EXISTS = 418
    CONFLICT_RESOLVED_WITH_MERGE = 419
    DEVICE_FULL = 420
    UNKNOWN_SEARCH_GRAMMAR = 421
    BAD_CGI = 422
    SOFT_DELETE_CONFLICT = 423
    SIZE_MISMATCH = 424
    PERMISSION_DENIED = 425
    PARTIAL_ITEM_NOT_ACCEPTED = 426
    ITEM_NOT_EMPTY = 427
    MOVE_FAILED = 428

    COMMAND_FAILED = 500
    NOT_IMPLEMENTED = 501
    BAD_GATEWAY = 502
    SERVICE_UNAVAILABLE = 503
    GATEWAY_TIMEOUT = 504
    PROCESSING_ERROR = 506
    ATOMIC_FAILED = 507
    REFRESH_REQUIRED = 508
    DATA_STORE_FAILURE = 510
    SERVER_FAILURE = 511
    SYNC_FAILED = 512
    PROTOCOL_VERSION_NOT_SUPPORTED = 513
    OPERATION_CANCELLED_BY_USER = 514
    ATOMIC_ROLLBACK_FAILED = 516
    ATOMIC_RESPONSE_TOO_LARGE = 517

# OMA DM Alert Codes
class AlertCode:
    DISPLAY = 1100
    CONFIRM_OR_REJECT = 1101
    TEXT_INPUT = 1102
    SINGLE_CHOICE = 1103
    MULTIPLE_CHOICE = 1104
    CLIENT_INITIATED_MGMT = 1201
    NEXT_MESSAGE = 1222
    SESSION_ABORT = 1223
    CLIENT_EVENT = 1224
    NO_END_OF_DATA = 1225
    GENERIC_ALERT = 1226
